server:
  port: 8088

# 添加监控
spring:
  application:
    name: monitoring-prometheus-grafana


management:
  endpoints:
    web:
      exposure:
        # 将 Actuator 的 /actuator/prometheus 端点暴露出来
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}